apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-writer-frontend
  labels:
    app: email-writer-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-writer-frontend
  template:
    metadata:
      labels:
        app: email-writer-frontend
    spec:
      containers:
      - name: email-writer-frontend
        image: your-dockerhub-username/email-writer-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
